# fly.toml app configuration file generated for pwa-hn-next on 2023-07-10T15:08:36+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pwa-hn-next"
primary_region = "syd"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
